name: catgirls_anytime

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust :3
      uses: actions-rs/toolchain@v1
      with:
            profile: minimal
            toolchain: nightly
            override: true

    - name: https://youtu.be/2kacWA5adQw # you asked for this
      run: cargo install cargo-mommy
    - name: owo
      run: cargo-mommy build
    - name: nya~
      run: cargo-mommy test --verbose
